spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: bestbook
  profiles:
    active: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: foo0
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8084

logging:
  level:
    org.hibernate.SQL: debug
