spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: rental
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/reservation?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
producers:
  bootstrap-servers: 9090
  topic1:
    name: rental_rent
  topic2:
    name: rental_return
  topic3:
    name: overdue_clear
server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
